###################################
#      AkariArtifact  Config      #
###################################

###########
# Options #
###########

# 全局设置
Options:
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false